### PR TITLE
Add preliminary support for .NET 7.0 by fixing SimulateTimeout.

### LINKED ISSUE #154: SimulateTimeout doesn't work anymore with .NET 7
**Describe the bug**
SimulateTimeout() reports "Operation was canceled." This is because of this following check:
https://github.com/dotnet/runtime/blob/release/7.0/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L614

**To Reproduce**
Run the tests with .NET 7

**Background (please complete the following information):**
 - Version of dotnet core: 7

### PR DESCRIPTION
**Pull request by dnperfors**
Fixes #154

### CODE REVIEW

File: src/TestableHttpClient/Utils/CancellationTokenExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+{
+    private static FieldInfo? cancellationSourceField;
+
+    private static FieldInfo? CancellationSourceField
+    {
+        get
+        {
+            if (cancellationSourceField is null)
+            {
+                cancellationSourceField = typeof(CancellationToken).GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.DeclaredOnly).FirstOrDefault(x => x.FieldType == typeof(CancellationTokenSource));
```
Comment (dnperfors) [inline src/TestableHttpClient/Utils/CancellationTokenExtensions.cs:15]: Consider using `Single` instead, since we can fail hard when we can't find a field.
